### ISSUE TITLE
Тесты на соответствие структуре

### ISSUE THREAD

**Issue by in19farkt** [sk1e/life#3]
В некоторых тестах, например, компоненты control-panel и game, ты проверяешь полное соответствие отрисованного компонента на всю глубину. Это не правильно, компонент game знает что он содержит в себе два элемента ControlPanel и CellGridContainer, и он не должен знать полную структуру этих элементов, их структура должна тестироваться в их собственных тестах. 

Представь себе такую ситуацию, у тебя есть некий компонент А, который используется в пяти других компонентах. Все они протестированы на всю глубину. И как только ты решишь изменить структуру компонента А, тебе придется переписывать все тесты для всех компонентов использующих компонент А.

Здесь правильнее будет воспользоваться enzime.sallow и поискать внутри компоненты ControlPanel и CellGridContainer, без проверки внутренней структуры этих компонентов.

**Comment by sk1e** [comment]
Сделал через снапшоты и shallow-renderer из react-addons-test-utils. Так нормально?

**Comment by sk1e** [comment]
Переделал через enzyme.

**Comment by in19farkt** [comment]
Так лучше, но если ты решишь поменять местами элементы внутри компонента, у тебя функционал компонента не изменится, он по-прежнему будет рабочий, а тесты посыпятся, и придется лезть переписывать снэпшоты. В идеале нужно делать shallow и искать внутри жизненно важные элементы.
